# Mô hình bao gồm 2 Node 1 master và 1 backup và 1 app
Client  --->  VIP 10.10.10.100  
                 │
        ┌────────┴────────┐
        │                 │
 Node-A (10.10.10.11)  Node-B (10.10.10.12)
   • HAProxy              • HAProxy
   • Keepalived (MASTER)  • Keepalived (BACKUP)
   -------------------------------------------
   |              10.10.10.13                | 
   |              APP Server                 |
   |-----------------------------------------|
# update package
sudo apt update
sudo reboot
# Cài đặt gói cần thiết
sudo apt install -y haproxy keepalived curl net-tools
# Tắt IPv6 (tùy chọn) nếu bạn không dùng: sửa /etc/sysctl.conf và thêm
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1

Sau đó sudo sysctl -p

# Cấu hình HAProxy
# Tập tin: /etc/haproxy/haproxy.cfg (giống nhau trên hai node)
global
    log /dev/log local0
    log /dev/log local1 notice
    stats socket /run/haproxy/admin.sock mode 660 level admin
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5s
    timeout client  50s
    timeout server  50s
    retries  3

frontend fe_web
    bind *:80 #port này thay đổi của app frontend lưu ý đoạn này
    default_backend be_web

backend be_web
    balance roundrobin
    option httpchk GET /
    server web1 192.168.1.101:80 check
    server web2 192.168.1.102:80 check

listen stats
    bind *:8404
    stats enable
    stats uri /stats
    stats refresh 10s
# kiểm tra cấu hình

sudo haproxy -f /etc/haproxy/haproxy.cfg -c

# khởi động và bật tự động
sudo systemctl enable --now haproxy

# 3️⃣ Cấu hình Keepalived
3.1 Thông số chung
• VIP: 10.10.10.100/24
• NIC: ens33 (thay bằng card của bạn)
• Password VRRP: @HApass
• Priority: Node-A 150 (MASTER), Node-B 100 (BACKUP)
# 3.2 Node-A – /etc/keepalived/keepalived.conf
vrrp_script chk_haproxy {
    script "/usr/bin/pgrep haproxy"
    interval 2
    weight -20
}

vrrp_instance VI_1 {
    state MASTER
    interface ens33
    virtual_router_id 51
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass @HApass
    }
    virtual_ipaddress {
        10.10.10.100/24 dev ens33 # đoạn này chỉnh sửa VIP cần chỉnh.
    }
    track_script {
        chk_haproxy
    }
    notify_master "/etc/keepalived/master.sh"
    notify_backup "/etc/keepalived/backup.sh"
    notify_fault  "/etc/keepalived/fault.sh"
}

# 3.3 Node-B – /etc/keepalived/keepalived.conf
# Chỉ cần chỉnh đúng phần này
# Chỉ khác state và priority:
state BACKUP
priority 100
# (Các dòng còn lại giữ nguyên)
# 3.4 Script thông báo (tuỳ chọn)
Tạo /etc/keepalived/master.sh (tương tự cho backup/fault) để log:
#!/bin/bash
logger "[KEEPALIVED] Switched to MASTER on $(hostname)"

# sau đó phân quyền để thực thi 
sudo chmod +x /etc/keepalived/*.sh

# 3.5 Khởi động Keepalived
sudo systemctl enable --now keepalived

# 4️⃣ Kiểm tra & chạy thử
ping VIP IP 

#Failover test:

Trên Node-A: sudo systemctl stop haproxy hoặc sudo systemctl stop keepalived.
Quan sát Node-B: ip a sẽ thấy VIP chuyển sang Node-B trong vòng ~2 giây.
Truy cập lại VIP: dịch vụ vẫn hoạt động.
Failback: khôi phục HAProxy/Keepalived trên Node-A → VIP tự quay lại

# 5️⃣ Một số tuỳ chỉnh hữu ích
Mục tiêu | Tuỳ chỉnh | Ghi chú
HTTPS TLS | Thêm bind *:443 ssl crt /etc/ssl/haproxy.pem trong frontend | Nên dùng Let’s Encrypt
Email alert | Sử dụng email trong keepalived hoặc Zabbix/Prometheus | Giám sát chủ động
Tăng tính sẵn sàng | Thêm Node-C (priority 90) | Chỉ cần copy cấu hình

# 6️⃣ Khắc phục lỗi thường gặp
Triệu chứng | Nguyên nhân | Cách xử lý
VIP không ping được | Keepalived chưa chạy / sai interface | Kiểm tra systemctl status keepalived, sửa interface
VIP flapping liên tục | Trùng virtual_router_id hoặc advert_int khác | Đồng bộ thông số trên cả 2 node
HAProxy không khởi động | Lỗi cú pháp config | sudo haproxy -c -f /etc/haproxy/haproxy.cfg